spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeonardoBonacci/oogway-config-data    
#for demo effect - 
#          uri: file://ubuntu1/oogway-config-data    

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}
    
