server: 
  port: 8765

service:  
  oracle:
    url: http://oracle-service:4444

logstash:
  host: logstash-service
  port: 4560

logging: 
  level.guru.bonacci.oogway.jobs: INFO
  
tutor:
  cron: 0 * * * * * 