sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
  - secure: 0LExc/WZjiS2XJrWT61Ji5lE89Ybdr6+4VH9aQq95GszQANR3K45FXmo4FO64KQmvo7lg0YGz7ZLOwTSsSurdD5e7RgPowL4uXWdn6IjQWKdW8SGDxsvtxkYPg2+2GZXGPGJMV6TSQ51wex7UO8Ej/0dcBguHi4SiXRWZEkrjU64HURdmEIZzOo7NnHLKDGvotckAVeXQ/YeZOuIorS6TpZXW4jq+9C8Lwr4R4Q4uHNdbv3IlxE4iPm9fuMql1JI75odoyBqcOkbQ4T0kWEUWZCAWArLw2YdGxlmHn/+48OUp5X6/uxmaEH9Kr/u4RoEK4PJx7dmhQggh8mmYqWVAzcrb/YiHcOfzi6GVzkNiJ1PwZBR9jaOem7O2ooxpkJtPREkObKZNA62tJF2GR1WmRtjHnWyi1hJ70uzKHlaQyFMIVzshmnPxWaAlVZjQVaj6mDb/TeumkFFCvf5aG0DFPnLAdX1Xtvoop6cxYV1zayJqyI95e7KU57dDQmGx0m2XcMfpzMJWID+U72kE1W+UTygJhved+QYHotlOiiio7CiQ8BhzYDVBrmwPgrG9cHy0O2UgndCukDnvguQvBbNHifxp1XXqh2Vyj1HyHHfeGh+9iBOpDYY4GF2ZcTdwr4Vo3mjpUA5gaSgEvsL//8Ow4eXwfezx+2X/8bouJsLguw= # DOCKER_USER
  - secure: T4BBuqlirH5Fh0GhimaxYkjfTH7KiEdEF7cVGzDig9074xG0l2zeNyOVzeG8xp7jz2NMIpDiVGvbGQ6n8EyFL5eorfPNE2Wx0LeZP0eDzFkwDZkF3oZEwvVpulsmrvrN83RheiugZ2He2SJoxzD/xmkaEAzqJO20WwPbpuzkVUqsxdafq6czWsFJMY+jDBSPVjB9QiD4Gnl0xxMbqcZ+MURvlb8yQSZqG0I8vMzG0Qr0hMOpLNcDjFSGJNIaIG7UNrHf7UHAprWpyJZfykjGM7rdr5Y2R0MvL6JvQm+uwhdFDN/PoUpxX0mK2re8g70ICW4/mE3VVHwH2h337GgrE1svLs8huPtHdudYzYQF/zQm5YVMikxWyrxt2ZNDdhC7KyQ7rZfiPmG4MwNaVUixK63Mq6hKz95ZJiNPHtrYC1selFHw5BUcnwlcO0AQvC0at2ma7qGpVGWbsiNBzyRJVsSbq/5R12WY4gfqDLptlEvtX1YFiG59ksEXJztEaih/Nef50KilAHYl6RrDwMB89invYdXnmMX4tXsdtNSZI0kaudImp2wk5Xvvs4NHSnKbi0KWVnVPGLWCRSjho69HaJtX1GgokQ26BQJ6Ep2Bg5IPJGuKhX2pLaBpW2yVUD47GiHChCzuNWsjt1FYcWO61QMkd1Ooghj3pnJi2hicwQs= # DOCKER_PASS

before_install:
  - chmod +x mvnw
  - docker login -u $DOCKER_USER -p $DOCKER_PASS


