version: '2.3'
services:

  rabbit:
    image: rabbitmq:3.7.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  doorway:
    image: leonardobonacci/oogway-doorway-service
    build: heimdall/doorway
    ports:
      - "3333:3333"

  lumberjack:
    image: leonardobonacci/oogway-lumberjack-service
    build: heimdall/lumberjack

  jobs:
    image: leonardobonacci/oogway-jobs-service
    build: jobs

  oracle:
    image: leonardobonacci/oogway-oracle-service
    build: oracle

  sannyas:
    image: leonardobonacci/oogway-sannyas-service
    build: sannyas
  
  localtimer:
    image: leonardobonacci/oogway-localtimer-service
    build: spectre/local-timer

  sentiment:
    image: leonardobonacci/oogway-sentiment-service
    build: spectre/sentiment

  weather:
    image: leonardobonacci/oogway-weather-service
    build: spectre/weather
      
  money:
    image: leonardobonacci/oogway-money-service
    build: spectre/money