version: '2.3'
services:

  doorway:
    image: leonardobonacci/oogway-doorway-service
    build: heimdall/doorway

  oracle:
    image: leonardobonacci/oogway-oracle-service
    build: oracle

  sannyas:
    image: leonardobonacci/oogway-sannyas-service
    build: sannyas