version: '2.1'
services:

  es:
    image: elasticsearch:2.4
    restart: always
#    volumes: 
#      - ${ES_PATH_DATA}:/usr/share/elasticsearch/data 
    ports:
      - 9200:9200
      - 9300:9300

  rabbit:
    image: rabbitmq:3.6-management
    restart: always
    ports:
      - 4369:4369 
      - 5672:5672 
      - 15672:15672 
      - 25672:25672 

  kibana:
    environment:
      ELASTICSEARCH_URL: http://es:9200
    image: kibana:4.6
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - es      

  logstash: 
    image: leonardobonacci/pruning-logstash:1.0
    restart: always
    volumes: 
      - ./logstash/pipeline:/usr/share/logstash/pipeline/:ro 
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    ports: 
      - 4560:4560
    depends_on:
      - es
      - rabbit

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: config
    restart: always

  orchestration-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: orchestration-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 1111:1111
      
  heimdall:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: heimdall
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9090:9090
      
  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 5000:5000

  web-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: web-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 3333:3333

  oracle-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: oracle-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      es:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 4444:4444

  sannyas-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: sannyas-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 2222:2222

  job-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: job-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8765:8765

  localtimer-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: localtimer-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 6666:6666

  money-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: money-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 11111:11111

  sentiment-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: sentiment-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 7777:7777

  weather-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
    image: weather-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 9999:9999

  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411
      
#  tor: 
#    image: osminogin/tor-simple
#    ports:
#      - 127.0.0.1:9050:9050 