#SET BROKER_HOST=123.456.78.90
version: '2.3'

services:

  db:
    image: postgres:latest
    container_name: some-postgres
    restart: always
    environment:
      POSTGRES_USER: demo 
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: pw
    ports:
      - "80:80"
      
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      
  doorway:
    image: leonardobonacci/oogway-doorway-service
    build: doorway
    ports:
      - 3333:3333
    extra_hosts:  
     - "kafka:${BROKER_HOST}"

  oracle:
    image: leonardobonacci/oogway-oracle-service
    build: oracle
    extra_hosts:  
     - "kafka:${BROKER_HOST}"
    depends_on:
      es:
        condition: service_started
    ports:
      - 4444

  sannyas:
    image: leonardobonacci/oogway-sannyas-service
    build: sannyas
    extra_hosts:  
     - "kafka:${BROKER_HOST}"
    
  no-curser:
    image: leonardobonacci/oogway-no-curser-service
    build: curse-guardian
    extra_hosts:  
     - "kafka:${BROKER_HOST}"
  
  enricher:
    image: leonardobonacci/oogway-enricher-service
    build: enricher
    extra_hosts:  
     - "kafka:${BROKER_HOST}"
  
  words:
    image: leonardobonacci/oogway-words-service
    build: word-counter
    extra_hosts:  
     - "kafka:${BROKER_HOST}"
    