version: '2.3'
services:

  auth:
    image: leonardobonacci/oogway-auth-service
    build: auth
            
  doorway:
    image: leonardobonacci/oogway-doorway-service
    build: heimdall/doorway

  lumberjack:
    image: leonardobonacci/oogway-lumberjack-service
    build: heimdall/lumberjack

  oracle:
    image: leonardobonacci/oogway-oracle-service
    build: oracle

#  sannyas:
#    image: leonardobonacci/oogway-sannyas-service
#    build: sannyas
  
  job:
    image: leonardobonacci/oogway-job-service
    build: jobs
  
  localtimer:
    image: leonardobonacci/oogway-localtimer-service
    build: spectre/local-timer

  sentiment:
    image: leonardobonacci/oogway-sentiment-service
    build: spectre/sentiment

  weather:
    image: leonardobonacci/oogway-weather-service
    build: spectre/weather
      
  money:
    image: leonardobonacci/oogway-money-service
    build: spectre/money

#  -- experimental feature working since upgrade --
#  tor: 
#    image: osminogin/tor-simple
#    ports:
#      - 127.0.0.1:9050:9050     