version: '2.3'
services:

#  gateway-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
#      SPRING_PROFILES_ACTIVE: dev
#    image: leonardobonacci/oogway-gateway-service
#    restart: always
#    depends_on:
#      config-service:
#        condition: service_healthy
#    ports:
#      - 80:9090
#      
  auth-service:
    image: leonardobonacci/oogway-auth-service
    build: auth
            
  doorway-service:
    image: leonardobonacci/oogway-doorway-service
    build: heimdall/doorway

  lumberjack-service:
    image: leonardobonacci/oogway-lumberjack-service
    build: heimdall/lumberjack

  oracle-service:
    image: leonardobonacci/oogway-oracle-service
    build: oracle

  sannyas-service:
    image: leonardobonacci/oogway-sannyas-service
    build: sannyas
  
  job-service:
    image: leonardobonacci/oogway-job-service
    build: jobs
  
  localtimer-service:
    image: leonardobonacci/oogway-localtimer-service
    build: spectre/local-timer

  sentiment-service:
    image: leonardobonacci/oogway-sentiment-service
    build: spectre/sentiment

  weather-service:
    image: leonardobonacci/oogway-weather-service
    build: spectre/weather
      
  money-service:
    image: leonardobonacci/oogway-money-service
    build: spectre/money

#  -- experimental feature working since upgrade --
#  tor: 
#    image: osminogin/tor-simple
#    ports:
#      - 127.0.0.1:9050:9050     