server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/

spring:
  application:
    name: zuul-server
    
zuul:
  ignoredServices: '*'

  routes:
    web-service:
        path: /webs/**
        serviceId: web-service
        stripPrefix: false
        sensitiveHeaders:

    static:
      path: /static/**
