server: 
  port: 7777

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
  configuration:
      commit.interval.ms: 1000
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.input.consumer.application-id: word-counter
spring.cloud.stream.bindings.output.destination: counts
spring.cloud.stream.bindings.input.destination: quote
spring.cloud.stream.bindings.input1.destination: counts
spring.cloud.stream.bindings.input1.binder: kafka


logging: 
  level: 
    root: WARN
    org.springframework: INFO
    guru.bonacci.oogway.words: INFO
