server.port: 3333

spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
spring.cloud.stream.bindings.output:
  destination: postum-enquiryevent
  producer:
    headerMode: raw
    nativeEncoding: true
spring.cloud.stream.bindings.input:
  destination: postum-enquiryevent
  group: doorway
  consumer:
    headerMode: raw
    nativeDecoding: true

service:  
  oracle:
    enabled: true
    name: oracle-service
    url: http://localhost:4444


logging: 
  level: 
    root: WARN
    org.springframework: INFO
    guru.bonacci.oogway.doorway: INFO


file.name.answers.to.win.time: answers-to-win-time.txt 