server.port: 2222

spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.input:
  destination: enquirys
  group: sannyas
  consumer:
    headerMode: raw
    useNativeDecoding: true
spring.cloud.stream.bindings.output:
  destination: quotes
  producer:
    headerMode: raw
    useNativeDecoding: true


logging:
  level.guru.bonacci.oogway.sannyas: INFO

# URLs of web pages we visit
web:
  url:
    gr: https://www.goodreads.com/quotes/tag/

# Filter configs
filter:
  maxlength: 144