server:
  port: 2222


spring:
  kafka: 
    bootstrap-servers: localhost:9092


spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.input.consumer.application-id: sannyas
spring.cloud.stream.bindings.input:
  destination: enquiry
spring.cloud.stream.bindings.output:
  destination: words


logging:
  level.guru.bonacci.oogway.sannyas: INFO

# URLs of web pages we visit
web:
  url:
    gr: https://www.goodreads.com/quotes/tag/

# Filter configs
filter:
  maxlength: 144
  profanity.file.name: badwords.txt  