server:
  port: 2222

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
  configuration:
      commit.interval.ms: 1000
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.input.consumer.application-id: sannyas
spring.cloud.stream.bindings.input.destination: enquiry
spring.cloud.stream.bindings.output.destination: quote


logging:
  level.guru.bonacci.oogway.sannyas: INFO

# URLs of web pages we visit
web:
  url:
    gr: https://www.goodreads.com/quotes/tag/

# Filter configs
filter:
  maxlength: 144