
spring.cloud.stream.kafka.binder.brokers: kafka
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde: org.springframework.kafka.support.serializer.JsonSerde

spring.cloud.stream.bindings.input:
  destination: enquiries
  contentType: application/json 
  group: sannyas
  consumer.headerMode: raw
spring.cloud.stream.bindings.output:
  destination: quotes
  contentType: application/json #default
  producer.headerMode: raw


logging:
  level.guru.bonacci.oogway.sannyas: INFO

# URLs of web pages we visit
web:
  url:
    gr: https://www.goodreads.com/quotes/tag/

# Filter configs
filter:
  maxlength: 144