# Spring properties
spring: 
  application: 
    name: localtimer-service

# HTTP Server
server: 
  port: 6666

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/
    instance: 
      leaseRenewalIntervalInSeconds: 5

#maven info
build: 
  version: "@project.version@"

#logging
logging: 
  level: 
    root: WARN
    org: 
      springframework: INFO
    guru: 
      bonacci: 
        spectre: 
          localtimer: INFO
  file: C:\\logs\\spectre\\localtimer.log
