# Spring properties
spring:
  application:
    name: sannyas-service
  data:
    elasticsearch:
      cluster-name: delphi
      cluster-nodes: localhost:9300

# HTTP Server
server:
  port: 2222

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 5

#maven info
build:
  version: "@project.version@"

#logging
logging:
  level:
    root: WARN
    org:
      springframework: INFO
    guru:
      bonacci:
        oogway:
          sannya: INFO
  file: C:\\logs\\oogway\\sannya.log
