spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
  configuration:
      commit.interval.ms: 1000
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.input.destination: quote
spring.cloud.stream.bindings.output.destination: decent

logging: 
  level: 
    root: WARN
    org.springframework: INFO
    guru.bonacci.oogway.curseguardian: INFO

    # Filter configs
filter:
  profanity.file.name: badwords.txt  