
spring.cloud.stream.kafka.binder.brokers: kafka
spring.cloud.stream.kafka.streams.binder.brokers: kafka
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde: org.springframework.kafka.support.serializer.JsonSerde

spring.cloud.stream.bindings.input:
  destination: quotes
  contentType: application/json 
  group: cursings
  consumer.headerMode: raw
spring.cloud.stream.bindings.output:
  destination: decent-quotes
  contentType: application/json 
  producer.headerMode: raw


logging: 
  level: 
    root: WARN
    org.springframework: INFO
    guru.bonacci.oogway.curseguardian: INFO

# Filter configs
filter:
  profanity.file.name: badwords.txt  