server:
  port: 5000
  servlet:
    context-path: /auth

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/auth/users/current

logging: 
  level:
    org.springframework.security: DEBUG
    guru.bonacci.oogway.auth: DEBUG