server: 
  port: 3333

#maven info
build: 
  version: "@project.version@"

#logging
logging: 
  level: 
    root: WARN
    org: 
      springframework: INFO
    guru: 
      bonacci: 
        oogway: 
          web: INFO
  file: C:\\logs\\oogway\\web.log
  
  