# Spring properties
spring:
  application:
    name: the-orchestrator

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
           
server:
  port: 1111

#logging
logging:
  level:
    root: WARN
  org:
    springframework:
      web: INFO
  guru: 
    bonacci: 
      oogway: 
        orchestration: INFO
  file: C:\\logs\\oogway\\orchestration.log
