server: 
  port: 7777

elasticsearch:
  hosts:
    - http://es:9200
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000

spring:
  rabbitmq:
    host: rabbit
  cloud:
    stream:
# no content-type:json here. the message is sent from logstash where headers cannot be set
      default:
        contentType: null
      bindings:
        enrichment:
          group: sentiment
        output:
          destination: spectre.sink

logstash:
  host: logstash-service
  port: 4560

logging: 
  level.guru.bonacci.spectre.sentiment: INFO
   
