eureka: 
  instance: 
    leaseRenewalIntervalInSeconds: 5
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/
      
spring:
  cloud:
    stream:
      default:
        contentType: application/json
        binder: rabbit

logging: 
  level: 
    root: WARN
    org.springframework: INFO