apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: http
# for testing purposes
    port: 80
#    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300