apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tutor
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tutor
            image: leonardobonacci/oogway-tutor-service
            imagePullPolicy: Never
          restartPolicy: OnFailure