apiVersion: v1
kind: Service
metadata:
  name: jobs-service
spec:
  selector:
    app: jobs
  ports:
  - protocol: TCP
    port: 8765
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs
spec:
  selector:
      matchLabels:
        app: jobs
  replicas: 1
  template:
    metadata:
      labels:
        app: jobs
    spec:
      containers:
        - name: oracle
          image: leonardobonacci/oogway-jobs-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8765
          volumeMounts:
          - name: app-config
            mountPath: /config
      volumes:
      - name: app-config
        configMap:
          name: jobs
