server: 
  port: 3333

spring:
  rabbitmq:
    host: rabbit
  cloud:
    stream:
      default:
        contentType: application/json
        binder: rabbit
      rabbit:
        bindings:
          spectre:
            producer:
              exchangeType: direct
              routingKeyExpression: '''eavesdrop'''
      bindings:
        input:
          destination: spectre.sink

service:  
  lumberjack:
    enabled: false
    name: lumberjack-service
    url: http://lumberjack-service:11235
  oracle:
    enabled: false
    name: oracle-service
    url: http://oracle-service:4444
  spectre:
    enabled: true

logstash:
  host: logstash-service
  port: 4560
      
logging: 
  level: 
    root: WARN
    org.springframework: INFO
    guru.bonacci.oogway.doorway: INFO


file.name.answers.to.win.time: answers-to-win-time.txt 