server: 
  port: 3333
  servlet:
    context-path: /doors

service:  
  lumberjack:
    name: lumberjack-service
    url: http://lumberjack-service:11235
  oracle:
    name: oracle-service
    url: http://oracle-service:4444
  auth:
    name: auth-service
    url: http://auth-service:5000

security:
  oauth2:
    client:
      clientId: doorway-service
      clientSecret: doorway-service-secret
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      scope: resource-server-read

#logstash:
#  host: logstash
#  port: 4560
      
logging: 
  level: 
    root: WARN
    org.springframework: INFO
    guru.bonacci.oogway.doorway: INFO

lumbering.enabled: false  
file.name.answers.to.win.time: answers-to-win-time.txt 