server: 
  port: 4444

elasticsearch:
  hosts:
    - http://es:9200
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000

service:  
  sannyas:
    enabled: true
    url: http://sannyas-service:2222

logstash:
  host: logstash-service
  port: 4560
    
logging: 
  level.guru.bonacci.oogway.oracle: INFO