server: 
  port: 4444

elasticsearch:
  hosts:
    - http://es:9200
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000

service:  
  sannyas:
    enabled: false
    url: http://sannyas-service:2222

logstash:
  host: logstash-service
  port: 4560
    
logging: 
  level.guru.bonacci.oogway.oracle: INFO

#https://github.com/nurkiewicz/elastic-flux/blob/micrometer/src/main/docs/grafana-elastic-flux-micrometer.json  
#spring.metrics.export.graphite:
#  host: 192.168.99.100
#  port: 2003
#  protocol: Plaintext
#  step: PT1S  