server:
  port: 11235
  servlet:
    context-path: /lumber

spring:
  data:
    mongodb:
      host: mongodb-service
      database: admin
      port: 27017
      username: main_admin
      password: abc123

logstash:
  host: logstash-service
  port: 4560

logging: 
  level.guru.bonacci.oogway.lumberjack: INFO  