server:
  port: 11235

spring:
  application:
    name: lumberjack
  data:
    mongodb:
      host: mongo
      database: oogway
      port: 27017

eureka:
  instance:
    prefer-ip-address: true
  client: 
    serviceUrl: 
      defaultZone: http://orchestration-service:1111/eureka/

logging: 
  level.guru.bonacci.oogway.lumberjack: INFO
