hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/

spring:
  application:
    name: zuul-server
    
zuul:
  ignoredServices: '*'

  routes:
    auth-service:
        path: /auth/**
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:
  
    web-service:
        path: /webby/**
        serviceId: web-service
        stripPrefix: false
        sensitiveHeaders:

    oracle-service:
        path: /oracle/**
        serviceId: oracle-service
        stripPrefix: false
        sensitiveHeaders:

    sannyas-service:
        path: /sannyas/**
        serviceId: sannyas-service
        stripPrefix: false
        sensitiveHeaders:
        